# Generated by Django 2.2 on 2019-05-09 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksiteadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('date_posted', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('documet_format', models.CharField(choices=[('APA', 'APA'), ('MLA', 'MLA'), ('Chicago', 'Chicago'), ('Havard', 'Havard')], default='APA', max_length=100)),
                ('task_file', models.FileField(blank=True, max_length=150, null=True, upload_to='Tasks/')),
                ('is_taken', models.BooleanField(default=False)),
                ('best_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worksiteadmin.SkillSet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('highest_education_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worksiteadmin.EducationLevelSet')),
            ],
        ),
    ]
