# Generated by Django 2.2 on 2019-05-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20190522_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
