# Generated by Django 2.2 on 2019-06-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_task_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='documet_format',
            field=models.CharField(choices=[('None', 'None'), ('APA', 'APA'), ('MLA', 'MLA'), ('Chicago', 'Chicago'), ('Havard', 'Havard')], default='None', max_length=100),
        ),
    ]
