# Generated by Django 2.2 on 2019-06-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20190608_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.FloatField(),
        ),
    ]
