# Generated by Django 2.2 on 2019-06-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20190610_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
