# Generated by Django 2.2 on 2019-05-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksiteadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationlevelset',
            old_name='highest_education_level',
            new_name='education_levels',
        ),
        migrations.RenameField(
            model_name='skillset',
            old_name='best_skill',
            new_name='skills',
        ),
    ]
