# Generated by Django 2.2 on 2019-05-13 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='best_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worksiteadmin.SkillSet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='highest_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worksiteadmin.EducationLevelSet'),
        ),
    ]
