# Generated by Django 2.2 on 2019-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidded',
            field=models.BooleanField(default=False),
        ),
    ]
