# Generated by Django 2.2 on 2019-05-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_bid_bidded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
