# Generated by Django 2.2 on 2019-05-25 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0006_bid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 5, 25, 14, 38, 0, 913055, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
