# Generated by Django 2.2 on 2019-05-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0008_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
