# Generated by Django 2.2 on 2019-05-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0009_auto_20190527_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
