# Generated by Django 2.2 on 2019-05-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0010_completed_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed',
            name='show',
        ),
    ]
