# Generated by Django 2.2 on 2019-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0011_remove_completed_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
