# Generated by Django 2.2 on 2019-05-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0012_completed_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed',
            name='show',
        ),
        migrations.AddField(
            model_name='bid',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
