# Generated by Django 2.2 on 2019-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0013_auto_20190527_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='file',
            field=models.FileField(default='no files', max_length=255, upload_to='Tasks/Completed'),
        ),
    ]
