# Generated by Django 2.2 on 2019-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0014_auto_20190528_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='file',
            field=models.FileField(max_length=255, upload_to='Tasks/Completed'),
        ),
    ]
