# Generated by Django 2.2 on 2019-05-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0015_auto_20190528_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completed',
            name='description',
            field=models.TextField(default='Work Complete', max_length=500),
        ),
        migrations.AlterField(
            model_name='completed',
            name='rating',
            field=models.DecimalField(blank=True, choices=[('5.00', 'Excellent'), ('4.00', 'Good'), ('3.00', 'Average'), ('2.00', 'Weak'), ('1.00', 'Poor')], decimal_places=2, max_digits=3, null=True),
        ),
    ]
