# Generated by Django 2.2 on 2019-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0020_auto_20190530_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidded',
            field=models.BooleanField(default=False),
        ),
    ]
