# Generated by Django 2.2 on 2019-06-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0022_remove_completed_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='rating',
            field=models.FloatField(blank=True, choices=[(5.0, 'Excellent'), (4.0, 'Good'), (3.0, 'Average'), (2.0, 'Weak'), (1.0, 'Poor')], null=True),
        ),
    ]
