# Generated by Django 2.2 on 2019-06-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0023_completed_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceraccountsummery',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
