# Generated by Django 2.2 on 2019-06-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0024_auto_20190608_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceraccountsummery',
            name='amount',
            field=models.FloatField(),
        ),
    ]
