# Generated by Django 2.2 on 2019-06-17 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelancer', '0025_auto_20190608_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReassigendTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
                ('reasons', models.CharField(max_length=255)),
                ('rating', models.FloatField(blank=True, choices=[(5.0, 'Excellent'), (4.0, 'Good'), (3.0, 'Average'), (2.0, 'Weak'), (1.0, 'Poor')], null=True)),
                ('files', models.FileField(max_length=255, upload_to='Tasks/Completed/Reassigned')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.Bid')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassigned_freelancer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
