# Generated by Django 2.2 on 2019-06-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0026_reassigendtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reassigendtask',
            old_name='files',
            new_name='file',
        ),
    ]
