# Generated by Django 2.2 on 2019-06-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0029_auto_20190617_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassigendtask',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freelancer.Bid'),
        ),
    ]
