# Generated by Django 2.2 on 2019-06-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0033_auto_20190618_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
