# Generated by Django 2.2 on 2019-06-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0034_bid_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='late_submission',
            field=models.BooleanField(default=False),
        ),
    ]
