# Generated by Django 2.2 on 2019-06-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0035_bid_late_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceraccountsummery',
            name='fines',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
